config/routes.rb
Rails.application.routes.draw do
  get 'descargar/index'

  resources :lugars

  resources :fechas

  resources :textos

  resources :usuarios

  get 'welcome/index'

  root 'welcome#index'

end

app/models/fecha.rb
class Fecha < ActiveRecord::Base
  belongs_to :texto
end

app/controllers/fechas_controller.rb
class FechasController < ApplicationController
  before_action :set_fecha, only: [:show, :edit, :update, :destroy]

  # GET /fechas
  # GET /fechas.json
  def index
    @fechas = Fecha.all
  end

  # GET /fechas/1
  # GET /fechas/1.json
  def show
  end

  # GET /fechas/new
  def new
    @fecha = Fecha.new
  end

  # GET /fechas/1/edit
  def edit
  end

  # POST /fechas
  # POST /fechas.json
  def create
    @fecha = Fecha.new(fecha_params)

    respond_to do |format|
      if @fecha.save
        format.html { redirect_to @fecha, notice: 'Fecha was successfully created.' }
        format.json { render :show, status: :created, location: @fecha }
      else
        format.html { render :new }
        format.json { render json: @fecha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fechas/1
  # PATCH/PUT /fechas/1.json
  def update
    respond_to do |format|
      if @fecha.update(fecha_params)
        format.html { redirect_to @fecha, notice: 'Fecha was successfully updated.' }
        format.json { render :show, status: :ok, location: @fecha }
      else
        format.html { render :edit }
        format.json { render json: @fecha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fechas/1
  # DELETE /fechas/1.json
  def destroy
    @fecha.destroy
    respond_to do |format|
      format.html { redirect_to fechas_url, notice: 'Fecha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fecha
      @fecha = Fecha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fecha_params
      params.require(:fecha).permit(:fecha)
    end
end

app/helpers/fechas_helper.rb
module FechasHelper
end

app/views/fechas/_form.html.erb
<%= form_for(@fecha) do |f| %>
  <% if @fecha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fecha.errors.count, "error") %> prohibited this fecha from being saved:</h2>

      <ul>
      <% @fecha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.datetime_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fechas/edit.html.erb
<h1>Editing fecha</h1>

<%= render 'form' %>

<%= link_to 'Show', @fecha %> |
<%= link_to 'Back', fechas_path %>

app/views/fechas/index.html.erb
<h1>Listing fechas</h1>

<table>
  <thead>
    <tr>
      <th style="background-color:#5D9F07">Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fechas.each do |fecha| %>
      <tr>
        <td><%= fecha.fecha %></td>
        <td><%= link_to 'Ver', fecha %></td>
        <td><%= link_to 'Editar', edit_fecha_path(fecha) %></td>
        <td><%= link_to 'Destruir', fecha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fecha', new_fecha_path %>

app/views/fechas/new.html.erb
<h1>New fecha</h1>

<%= render 'form' %>

<%= link_to 'Back', fechas_path %>

app/views/fechas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @fecha.fecha %>
</p>

<%= link_to 'Edit', edit_fecha_path(@fecha) %> |
<%= link_to 'Back', fechas_path %>