config/routes.rb
Rails.application.routes.draw do
  get 'descargar/index'

  resources :lugars

  resources :fechas

  resources :textos

  resources :usuarios

  get 'welcome/index'

  root 'welcome#index'

end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
  belongs_to :texto
end

app/controllers/lugars_controller.rb
class LugarsController < ApplicationController
  before_action :set_lugar, only: [:show, :edit, :update, :destroy]

  # GET /lugars
  # GET /lugars.json
  def index
    @lugars = Lugar.all
  end

  # GET /lugars/1
  # GET /lugars/1.json
  def show
  end

  # GET /lugars/new
  def new
    @lugar = Lugar.new
  end

  # GET /lugars/1/edit
  def edit
  end

  # POST /lugars
  # POST /lugars.json
  def create
    @lugar = Lugar.new(lugar_params)

    respond_to do |format|
      if @lugar.save
        format.html { redirect_to @lugar, notice: 'Lugar was successfully created.' }
        format.json { render :show, status: :created, location: @lugar }
      else
        format.html { render :new }
        format.json { render json: @lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lugars/1
  # PATCH/PUT /lugars/1.json
  def update
    respond_to do |format|
      if @lugar.update(lugar_params)
        format.html { redirect_to @lugar, notice: 'Lugar was successfully updated.' }
        format.json { render :show, status: :ok, location: @lugar }
      else
        format.html { render :edit }
        format.json { render json: @lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lugars/1
  # DELETE /lugars/1.json
  def destroy
    @lugar.destroy
    respond_to do |format|
      format.html { redirect_to lugars_url, notice: 'Lugar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lugar
      @lugar = Lugar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lugar_params
      params.require(:lugar).permit(:pais_nombre, :geo)
    end
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/views/lugars/_form.html.erb
<%= form_for(@lugar) do |f| %>
  <% if @lugar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lugar.errors.count, "error") %> prohibited this lugar from being saved:</h2>

      <ul>
      <% @lugar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pais_nombre %><br>
    <%= f.text_field :pais_nombre %>
  </div>
  <div class="field">
    <%= f.label :geo %><br>
    <%= f.text_field :geo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lugars/edit.html.erb
<h1>Editing lugar</h1>

<%= render 'form' %>

<%= link_to 'Show', @lugar %> |
<%= link_to 'Back', lugars_path %>

app/views/lugars/index.html.erb
<h1>Listing lugars</h1>

<table>
  <thead>
    <tr>
      <th style="background-color:#5D9F07">Pais nombre</th>
      <th style="background-color:#5D9F07">lat</th>
      <th style="background-color:#5D9F07">long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lugars.each do |lugar| %>
      <tr>
        <td><%= lugar.pais_nombre %></td>
        <td><%= lugar.lat %></td>
        <td><%= lugar.long %></td>
        <td><%= link_to 'Ver', lugar %></td>
        <td><%= link_to 'Editar', edit_lugar_path(lugar) %></td>
        <td><%= link_to 'Destruir', lugar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lugar', new_lugar_path %>

app/views/lugars/new.html.erb
<h1>New lugar</h1>

<%= render 'form' %>

<%= link_to 'Back', lugars_path %>

app/views/lugars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pais nombre:</strong>
  <%= @lugar.pais_nombre %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @lugar.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @lugar.long %>
</p>

<%= link_to 'Edit', edit_lugar_path(@lugar) %> |
<%= link_to 'Back', lugars_path %>